### ISSUE TITLE
Add feature to allow users to specify opacity value when requesting icons

### ISSUE THREAD

**Issue by Jenton** [salesforce-ux/design-system-ios#11]
Is it possible to allow users to specify the opacity value when requesting icons from this repository? This would be extremely useful.

Thanks!

-Jenton

**Comment by kaelig** [comment]
@jandolina @erlswtshrt are you able to give an update on this?

**Comment by jandolina** [comment]
Alpha values are fully supported in the 3.0.0 release. There are two new functions which allow for icon alpha or icon and background alpha:
```
(SLDSActionIconType)iconType withColor:(UIColor*)iconColor andSize:(CGFloat)size;
(SLDSActionIconType)iconType withColor:(UIColor*)iconColor andBGColor:(UIColor*)bgColor andSize:(CGFloat)size;
```

All you need to do is pass colors with alpha values to the icon call

```
// Select (or create) colors with an alpha value
let bgColor = UIColor.sldsBackgroundColor(.colorBackgroundImageOverlay)
let fgColor = UIColor.sldsBackgroundColor(.colorBackgroundTempModalTint)
            
let myAlphaImage = UIImage.sldsActionIcon(.addContact, with: fgColor, andBGColor: bgColor, andSize: SLDSSquareIconLarge)

```            

Happy Coding
